#!/usr/bin/env perl
use strict;
use warnings;

use Dredd::Hooks;
use IO::All;
use JSON;
use Carp::Always;

my $hooks = Dredd::Hooks->new(hook_files => \@ARGV);
my $serialiser = JSON->new->convert_blessed->utf8;

print "Starting\n";

while (my $socket = io('127.0.0.1:61321')->accept){
    while (my $message = $serialiser->decode($socket->getline)){
        my $event = $message->{event};
        if ($event && (my $method = $hooks->can($event))){
            $socket->print(
                $serialiser->encode({
                    "uuid"  => $message->{uuid},
                    "event" => $message->{event},
                    "data"  => $hooks->$method($message->{data})
                })
                ."\n"
            );
        } else {
            $socket->print(JSON::encode_json($message));
        }
    }
}
