#!/usr/bin/env perl
use strict;
use warnings;

use Dredd::Hooks;
use IO::All;
use JSON;
use Carp::Always;

my $hooks = Dredd::Hooks->new(hook_files => [glob(join ' ', @ARGV)]);

my $serialiser = JSON->new->convert_blessed->utf8;
my $socket = io('127.0.0.1:61321');

{
    local $| = 1;
    print "Starting\n";
}

while (my $client = $socket->accept){
    while (my $message = $serialiser->decode($client->getline)){
        my $event = $message->{event};
        if ($event && (my $method = $hooks->can($event))){
            $client->print(
                $serialiser->encode({
                    "uuid"  => $message->{uuid},
                    "event" => $message->{event},
                    "data"  => $hooks->$method($message->{data})
                })
                ."\n"
            );
        } else {
            $client->print(JSON::encode_json($message));
        }
    }
    $client->close;
}
